{{- if .Values.gke.enabled -}}
apiVersion: v1
kind: PodMonitoring
metadata:
  name: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/monitoring: enabled
  endpoints:
    - port: metrics
      interval: 30s
{{- end }}
