replicaCount: 1
image:
  repository: ghcr.io/toeverything/affine-graphql
  pullPolicy: IfNotPresent
  tag: ''

imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
# map to NODE_ENV environment variable
env: 'production'
database:
  user: 'postgres'
  url: 'pg-postgresql'
  port: '5432'
  name: 'affine'
redis:
  enabled: true
  host: 'redis-master'
  port: '6379'
  username: ''
  password: ''
  database: 0
app:
  # AFFINE_SERVER_HOST
  host: '0.0.0.0'

serviceAccount:
  create: true
  annotations: {}
  name: 'affine-sync'

podAnnotations: {}

podSecurityContext:
  fsGroup: 2000

resources:
  limits:
    cpu: '8'
    memory: 8Gi
  requests:
    cpu: '4'
    memory: 8Gi

probe:
  initialDelaySeconds: 20

nodeSelector: {}
tolerations: []
affinity: {}
