name: Setup maker
description: 'Setup maker dmg for electron'
runs:
  using: 'composite'
  steps:
    - name: 'Install @electron-forge/maker-dmg'
      if: runner.os == 'macos'
      shell: bash
      working-directory: ./apps/electron
      run: yarn add @electron-forge/maker-dmg --dev
