name: Update block-suite version

on:
  schedule:
    # At 02:00 UTC
    - cron: '0 2 * * *'
  workflow_dispatch:

# Cancels all previous workflow runs for pull requests that have not completed.
# See https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  # The concurrency group contains the workflow name and the branch name for
  # pull requests or the commit hash for any other events.
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Use Node.js 18
        # https://github.com/actions/setup-node
        uses: actions/setup-node@v3
        with:
          node-version: '18.X'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Get old version
        id: old-version
        run: |
          PACKAGE_VERSION=$(cat apps/web/package.json | jq '.version.dependencies.@blocksuite/editor' | tr -d '"')
          echo "old-version=${PACKAGE_VERSION}" >> $GITHUB_OUTPUT

      - name: Update block-suite version
        run: pnpm update:core

      - name: Get new version
        id: new-version
        run: |
          PACKAGE_VERSION=$(cat apps/web/package.json | jq '.version.dependencies.@blocksuite/editor' | tr -d '"')
          echo "new-version=${PACKAGE_VERSION}" >> $GITHUB_OUTPUT

      # https://github.com/devops-infra/action-commit-push
      - name: Commit push
        uses: devops-infra/action-commit-push@master
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          commit_message: 'chore: bump blocksuite from ${{ steps.old-version.outputs.old-version }} to ${{ steps.new-version.outputs.new-version }}'
          force: true
          target_branch: bot/bump-core

      # https://github.com/devops-infra/action-pull-request
      - name: Create pull request
        uses: devops-infra/action-pull-request@v0.5.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title: 'Bump blocksuite from ${{ steps.old-version.outputs.old-version }} to ${{ steps.new-version.outputs.new-version }}'
          body: 'Please carefully check the editor functionality before merging the PR.'
