name: Windows Signer
on:
  workflow_call:
    inputs:
      artifact-name:
        required: true
        type: string
      files:
        required: true
        type: string
jobs:
  sign:
    runs-on: [self-hosted, win-signer]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
          path: app-dir
      - name: unzip file
        run: 7za x app-dir/archive.zip app-dir/out
      - name: sign
        run: |
          # sign all binary files
          signtool sign /tr http://timestamp.sectigo.com /td sha256 /fd sha256 /a ${{ inputs.files }}
      - name: zip file
        run: Compress-Archive -Path app-dir -DestinationPath signed.zip
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: signed-${{ github.event.inputs.artifact-name }}
          path: signed.zip
