name: Windows Signer
on:
  workflow_call:
    inputs:
      artifact-name:
        required: true
        type: string
      files:
        required: true
        type: string
jobs:
  sign:
    runs-on: [self-hosted, win-signer]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
          path: .
      - name: unzip file
        shell: cmd
        run: 7za x archive.zip ./out
      - name: sign
        shell: cmd
        run: |
          cd ./out
          signtool sign /tr http://timestamp.sectigo.com /td sha256 /fd sha256 /a ${{ inputs.files }}
      - name: zip file
        shell: cmd
        run: Compress-Archive -Path ./out -DestinationPath signed.zip
      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: signed-${{ github.event.inputs.artifact-name }}
          path: signed.zip
